-- MySQL Script generated by MySQL Workbench
-- 01/25/15 13:38:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TSG
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `sgu_marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_marca` ;

CREATE TABLE IF NOT EXISTS `sgu_marca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_modelo` ;

CREATE TABLE IF NOT EXISTS `sgu_modelo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(45) NOT NULL,
  `idmarca` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SGU_modelo_SGU_marca1_idx` (`idmarca` ASC),
  CONSTRAINT `fk_SGU_modelo_SGU_marca1`
    FOREIGN KEY (`idmarca`)
    REFERENCES `sgu_marca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_tipo` ;

CREATE TABLE IF NOT EXISTS `sgu_tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_grupo` ;

CREATE TABLE IF NOT EXISTS `sgu_grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grupo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `idtipo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SGU_grupo_SGU_tipo1_idx` (`idtipo` ASC),
  CONSTRAINT `fk_SGU_grupo_SGU_tipo1`
    FOREIGN KEY (`idtipo`)
    REFERENCES `sgu_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_color` ;

CREATE TABLE IF NOT EXISTS `sgu_color` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_propiedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_propiedad` ;

CREATE TABLE IF NOT EXISTS `sgu_propiedad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `propiedad` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_tipoCombustible`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_tipoCombustible` ;

CREATE TABLE IF NOT EXISTS `sgu_tipoCombustible` (
  `id` INT NOT NULL,
  `combustible` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_vehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_vehiculo` ;

CREATE TABLE IF NOT EXISTS `sgu_vehiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numeroUnidad` INT NOT NULL,
  `serialCarroceria` VARCHAR(45) NOT NULL,
  `serialMotor` VARCHAR(45) NOT NULL,
  `placa` VARCHAR(7) NOT NULL,
  `anno` INT NOT NULL,
  `nroPuestos` INT NOT NULL,
  `nroEjes` INT NULL,
  `capCarga` INT NULL,
  `comentario` VARCHAR(200) NULL,
  `cantidadRuedas` INT NOT NULL,
  `capTanque` INT NOT NULL,
  `idmodelo` INT NOT NULL,
  `idgrupo` INT NOT NULL,
  `idcolor` INT NOT NULL,
  `idpropiedad` INT NOT NULL,
  `idcombustible` INT NOT NULL,
  `fechaRegistro` TIMESTAMP NULL,
  `KmInicial` INT NOT NULL,
  `rendimiento` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_SGU_vehiculo_SGU_modelo1_idx` (`idmodelo` ASC),
  UNIQUE INDEX `numeroUnidad_UNIQUE` (`numeroUnidad` ASC),
  INDEX `fk_SGU_vehiculo_SGU_grupo1_idx` (`idgrupo` ASC),
  INDEX `fk_SGU_vehiculo_SGU_color1_idx` (`idcolor` ASC),
  INDEX `fk_SGU_vehiculo_sgu_propiedad1_idx` (`idpropiedad` ASC),
  UNIQUE INDEX `serialCarroceria_UNIQUE` (`serialCarroceria` ASC),
  UNIQUE INDEX `serialChasis_UNIQUE` (`serialMotor` ASC),
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC),
  INDEX `fk_sgu_vehiculo_sgu_tipoCombustible1_idx` (`idcombustible` ASC),
  CONSTRAINT `fk_SGU_vehiculo_SGU_modelo1`
    FOREIGN KEY (`idmodelo`)
    REFERENCES `sgu_modelo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_SGU_vehiculo_SGU_grupo1`
    FOREIGN KEY (`idgrupo`)
    REFERENCES `sgu_grupo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_SGU_vehiculo_SGU_color1`
    FOREIGN KEY (`idcolor`)
    REFERENCES `sgu_color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SGU_vehiculo_sgu_propiedad1`
    FOREIGN KEY (`idpropiedad`)
    REFERENCES `sgu_propiedad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_vehiculo_sgu_tipoCombustible1`
    FOREIGN KEY (`idcombustible`)
    REFERENCES `sgu_tipoCombustible` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_foto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_foto` ;

CREATE TABLE IF NOT EXISTS `sgu_foto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imagen` MEDIUMTEXT NOT NULL,
  `idvehiculo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SGU_foto_SGU_vehiculo1_idx` (`idvehiculo` ASC),
  CONSTRAINT `fk_SGU_foto_SGU_vehiculo1`
    FOREIGN KEY (`idvehiculo`)
    REFERENCES `sgu_vehiculo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_TipoRepuesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_TipoRepuesto` ;

CREATE TABLE IF NOT EXISTS `sgu_TipoRepuesto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_subTipoRepuesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_subTipoRepuesto` ;

CREATE TABLE IF NOT EXISTS `sgu_subTipoRepuesto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idTipoRepuesto` INT NOT NULL,
  `subTipo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SGU_subTipoRepuesto_SGU_TipoRepuesto1_idx` (`idTipoRepuesto` ASC),
  CONSTRAINT `fk_SGU_subTipoRepuesto_SGU_TipoRepuesto1`
    FOREIGN KEY (`idTipoRepuesto`)
    REFERENCES `sgu_TipoRepuesto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_unidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_unidad` ;

CREATE TABLE IF NOT EXISTS `sgu_unidad` (
  `id` INT NOT NULL,
  `unidad` VARCHAR(30) NOT NULL,
  `corto` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_repuesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_repuesto` ;

CREATE TABLE IF NOT EXISTS `sgu_repuesto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `repuesto` VARCHAR(200) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `idsubTipoRepuesto` INT NOT NULL,
  `idunidad` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SGU_repuesto_SGU_subTipoRepuesto1_idx` (`idsubTipoRepuesto` ASC),
  UNIQUE INDEX `unicoSGU_repuesto` (`repuesto` ASC, `idsubTipoRepuesto` ASC),
  INDEX `fk_sgu_repuesto_sgu_unidad1_idx` (`idunidad` ASC),
  CONSTRAINT `fk_SGU_repuesto_SGU_subTipoRepuesto1`
    FOREIGN KEY (`idsubTipoRepuesto`)
    REFERENCES `sgu_subTipoRepuesto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sgu_repuesto_sgu_unidad1`
    FOREIGN KEY (`idunidad`)
    REFERENCES `sgu_unidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_estado` ;

CREATE TABLE IF NOT EXISTS `sgu_estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_parametro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_parametro` ;

CREATE TABLE IF NOT EXISTS `sgu_parametro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_Sinonimo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_Sinonimo` ;

CREATE TABLE IF NOT EXISTS `sgu_Sinonimo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sinonimo` VARCHAR(45) NOT NULL,
  `idrepuesto1` INT NOT NULL,
  `idrepuesto2` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SGU_Sinonimo_SGU_repuesto1_idx` (`idrepuesto1` ASC),
  INDEX `fk_SGU_Sinonimo_SGU_repuesto2_idx` (`idrepuesto2` ASC),
  CONSTRAINT `fk_SGU_Sinonimo_SGU_repuesto1`
    FOREIGN KEY (`idrepuesto1`)
    REFERENCES `sgu_repuesto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_SGU_Sinonimo_SGU_repuesto2`
    FOREIGN KEY (`idrepuesto2`)
    REFERENCES `sgu_repuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_CaracteristicaVeh`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_CaracteristicaVeh` ;

CREATE TABLE IF NOT EXISTS `sgu_CaracteristicaVeh` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL DEFAULT 1,
  `idvehiculo` INT NOT NULL,
  `idrepuesto` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SGU_CaracteristicaVeh_SGU_vehiculo1_idx` (`idvehiculo` ASC),
  INDEX `fk_SGU_CaracteristicaVeh_SGU_repuesto1_idx` (`idrepuesto` ASC),
  CONSTRAINT `fk_SGU_CaracteristicaVeh_SGU_vehiculo1`
    FOREIGN KEY (`idvehiculo`)
    REFERENCES `sgu_vehiculo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_SGU_CaracteristicaVeh_SGU_repuesto1`
    FOREIGN KEY (`idrepuesto`)
    REFERENCES `sgu_repuesto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_historicoEdos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_historicoEdos` ;

CREATE TABLE IF NOT EXISTS `sgu_historicoEdos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idestado` INT NOT NULL,
  `idvehiculo` INT NOT NULL,
  `fechaini` DATE NOT NULL,
  `fechafin` DATE NULL,
  `comentario` VARCHAR(200) NULL,
  `fechaRegistro` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SGU_historicoEdos_SGU_estado1_idx` (`idestado` ASC),
  INDEX `fk_SGU_historicoEdos_SGU_vehiculo1_idx` (`idvehiculo` ASC),
  CONSTRAINT `fk_SGU_historicoEdos_SGU_estado1`
    FOREIGN KEY (`idestado`)
    REFERENCES `sgu_estado` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_SGU_historicoEdos_SGU_vehiculo1`
    FOREIGN KEY (`idvehiculo`)
    REFERENCES `sgu_vehiculo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_medidaCaucho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_medidaCaucho` ;

CREATE TABLE IF NOT EXISTS `sgu_medidaCaucho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `medida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_rin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_rin` ;

CREATE TABLE IF NOT EXISTS `sgu_rin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rin` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_piso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_piso` ;

CREATE TABLE IF NOT EXISTS `sgu_piso` (
  `id` INT NOT NULL,
  `piso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_caucho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_caucho` ;

CREATE TABLE IF NOT EXISTS `sgu_caucho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idmedidaCaucho` INT NOT NULL,
  `idrin` INT NOT NULL,
  `idpiso` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_caucho_sgu_medidaCaucho1_idx` (`idmedidaCaucho` ASC),
  INDEX `fk_sgu_caucho_sgu_rin1_idx` (`idrin` ASC),
  INDEX `fk_sgu_caucho_sgu_piso1_idx` (`idpiso` ASC),
  CONSTRAINT `fk_sgu_caucho_sgu_medidaCaucho1`
    FOREIGN KEY (`idmedidaCaucho`)
    REFERENCES `sgu_medidaCaucho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_caucho_sgu_rin1`
    FOREIGN KEY (`idrin`)
    REFERENCES `sgu_rin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_caucho_sgu_piso1`
    FOREIGN KEY (`idpiso`)
    REFERENCES `sgu_piso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_marcaCaucho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_marcaCaucho` ;

CREATE TABLE IF NOT EXISTS `sgu_marcaCaucho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_departamento` ;

CREATE TABLE IF NOT EXISTS `sgu_departamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_CaracteristicaVehGrupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_CaracteristicaVehGrupo` ;

CREATE TABLE IF NOT EXISTS `sgu_CaracteristicaVehGrupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL DEFAULT 1,
  `idgrupo` INT NOT NULL,
  `idrepuesto` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SGU_CaracteristicaVehGrupo_SGU_grupo1_idx` (`idgrupo` ASC),
  INDEX `fk_SGU_CaracteristicaVehGrupo_SGU_repuesto1_idx` (`idrepuesto` ASC),
  UNIQUE INDEX `unicoSGU_CaracteristicaVehGrupo` (`idgrupo` ASC, `idrepuesto` ASC),
  CONSTRAINT `fk_SGU_CaracteristicaVehGrupo_SGU_grupo1`
    FOREIGN KEY (`idgrupo`)
    REFERENCES `sgu_grupo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_SGU_CaracteristicaVehGrupo_SGU_repuesto1`
    FOREIGN KEY (`idrepuesto`)
    REFERENCES `sgu_repuesto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_informacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_informacion` ;

CREATE TABLE IF NOT EXISTS `sgu_informacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `informacion` VARCHAR(60) NOT NULL,
  `descripcion` VARCHAR(80) NULL,
  `idvehiculo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_informacion_sgu_vehiculo1_idx` (`idvehiculo` ASC),
  CONSTRAINT `fk_sgu_informacion_sgu_vehiculo1`
    FOREIGN KEY (`idvehiculo`)
    REFERENCES `sgu_vehiculo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_Cantidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_Cantidad` ;

CREATE TABLE IF NOT EXISTS `sgu_Cantidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigoPiezaEnUso` VARCHAR(100) NULL,
  `detallePieza` VARCHAR(100) NULL,
  `fechaIncorporacion` DATE NULL,
  `idCaracteristicaVeh` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SGU_Cantidad_SGU_CaracteristicaVeh1_idx` (`idCaracteristicaVeh` ASC),
  CONSTRAINT `fk_SGU_Cantidad_SGU_CaracteristicaVeh1`
    FOREIGN KEY (`idCaracteristicaVeh`)
    REFERENCES `sgu_CaracteristicaVeh` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_CantidadGrupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_CantidadGrupo` ;

CREATE TABLE IF NOT EXISTS `sgu_CantidadGrupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `detallePieza` VARCHAR(100) NULL,
  `idCaracteristicaVehGrupo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SGU_CantidadGrupo_SGU_CaracteristicaVehGrupo1_idx` (`idCaracteristicaVehGrupo` ASC),
  CONSTRAINT `fk_SGU_CantidadGrupo_SGU_CaracteristicaVehGrupo1`
    FOREIGN KEY (`idCaracteristicaVehGrupo`)
    REFERENCES `sgu_CaracteristicaVehGrupo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_infGrupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_infGrupo` ;

CREATE TABLE IF NOT EXISTS `sgu_infGrupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `informacion` VARCHAR(60) NOT NULL,
  `idgrupo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_infGrupo_sgu_grupo1_idx` (`idgrupo` ASC),
  UNIQUE INDEX `informacion_UNIQUE` (`informacion` ASC),
  UNIQUE INDEX `idgrupo_UNIQUE` (`idgrupo` ASC),
  CONSTRAINT `fk_sgu_infGrupo_sgu_grupo1`
    FOREIGN KEY (`idgrupo`)
    REFERENCES `sgu_grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_prioridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_prioridad` ;

CREATE TABLE IF NOT EXISTS `sgu_prioridad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prioridad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_tiempo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_tiempo` ;

CREATE TABLE IF NOT EXISTS `sgu_tiempo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tiempo` VARCHAR(10) NOT NULL,
  `sqlTimevalues` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_actividadMtto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_actividadMtto` ;

CREATE TABLE IF NOT EXISTS `sgu_actividadMtto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `actividad` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_actividadesGrupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_actividadesGrupo` ;

CREATE TABLE IF NOT EXISTS `sgu_actividadesGrupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `procedimiento` VARCHAR(200) NULL,
  `frecuenciaKm` INT NOT NULL,
  `frecuenciaMes` INT NULL,
  `duracion` INT NOT NULL DEFAULT 0,
  `diasParo` INT NULL,
  `idprioridad` INT NOT NULL,
  `idtiempod` INT NOT NULL,
  `idtiempof` INT NOT NULL,
  `idactividadMtto` INT NOT NULL,
  `idgrupo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_actividadesGrupo_sgu_prioridad1_idx` (`idprioridad` ASC),
  INDEX `fk_sgu_actividadesGrupo_sgu_tiempo1_idx` (`idtiempod` ASC),
  INDEX `fk_sgu_actividadesGrupo_sgu_tiempo2_idx` (`idtiempof` ASC),
  INDEX `fk_sgu_actividadesGrupo_sgu_actividadMtto1_idx` (`idactividadMtto` ASC),
  INDEX `fk_sgu_actividadesGrupo_sgu_grupo1_idx` (`idgrupo` ASC),
  CONSTRAINT `fk_sgu_actividadesGrupo_sgu_prioridad1`
    FOREIGN KEY (`idprioridad`)
    REFERENCES `sgu_prioridad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_actividadesGrupo_sgu_tiempo1`
    FOREIGN KEY (`idtiempod`)
    REFERENCES `sgu_tiempo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_actividadesGrupo_sgu_tiempo2`
    FOREIGN KEY (`idtiempof`)
    REFERENCES `sgu_tiempo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_actividadesGrupo_sgu_actividadMtto1`
    FOREIGN KEY (`idactividadMtto`)
    REFERENCES `sgu_actividadMtto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_actividadesGrupo_sgu_grupo1`
    FOREIGN KEY (`idgrupo`)
    REFERENCES `sgu_grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_estatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_estatus` ;

CREATE TABLE IF NOT EXISTS `sgu_estatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_actividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_actividades` ;

CREATE TABLE IF NOT EXISTS `sgu_actividades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ultimoKm` INT NOT NULL DEFAULT -1,
  `ultimoFecha` DATE NOT NULL DEFAULT '0000-01-01',
  `frecuenciaKm` INT NOT NULL,
  `frecuenciaMes` INT NULL,
  `proximoKm` INT NULL,
  `proximoFecha` DATE NULL,
  `duracion` INT NOT NULL DEFAULT 0,
  `atraso` INT NULL,
  `idprioridad` INT NOT NULL,
  `idtiempod` INT NOT NULL,
  `idtiempof` INT NOT NULL,
  `idactividadesGrupo` INT NOT NULL,
  `idestatus` INT NOT NULL,
  `idactividadMtto` INT NOT NULL,
  `fechaRealizada` DATE NOT NULL DEFAULT '0000-01-01',
  `kmRealizada` INT NOT NULL DEFAULT -1,
  `procedimiento` VARCHAR(200) NULL,
  `idvehiculo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_actividades_sgu_prioridad1_idx` (`idprioridad` ASC),
  INDEX `fk_sgu_actividades_sgu_tiempo1_idx` (`idtiempod` ASC),
  INDEX `fk_sgu_actividades_sgu_tiempo2_idx` (`idtiempof` ASC),
  INDEX `fk_sgu_actividades_sgu_actividadesGrupo1_idx` (`idactividadesGrupo` ASC),
  INDEX `fk_sgu_actividades_sgu_estatus1_idx` (`idestatus` ASC),
  INDEX `fk_sgu_actividades_sgu_actividadMtto1_idx` (`idactividadMtto` ASC),
  INDEX `fk_sgu_actividades_sgu_vehiculo1_idx` (`idvehiculo` ASC),
  CONSTRAINT `fk_sgu_actividades_sgu_prioridad1`
    FOREIGN KEY (`idprioridad`)
    REFERENCES `sgu_prioridad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_actividades_sgu_tiempo1`
    FOREIGN KEY (`idtiempod`)
    REFERENCES `sgu_tiempo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_actividades_sgu_tiempo2`
    FOREIGN KEY (`idtiempof`)
    REFERENCES `sgu_tiempo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_actividades_sgu_actividadesGrupo1`
    FOREIGN KEY (`idactividadesGrupo`)
    REFERENCES `sgu_actividadesGrupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_actividades_sgu_estatus1`
    FOREIGN KEY (`idestatus`)
    REFERENCES `sgu_estatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_actividades_sgu_actividadMtto1`
    FOREIGN KEY (`idactividadMtto`)
    REFERENCES `sgu_actividadMtto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_actividades_sgu_vehiculo1`
    FOREIGN KEY (`idvehiculo`)
    REFERENCES `sgu_vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_tipoInsumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_tipoInsumo` ;

CREATE TABLE IF NOT EXISTS `sgu_tipoInsumo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_insumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_insumo` ;

CREATE TABLE IF NOT EXISTS `sgu_insumo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `insumo` VARCHAR(100) NOT NULL,
  `tipoInsumo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_insumo_sgu_tipoInsumo1_idx` (`tipoInsumo` ASC),
  CONSTRAINT `fk_sgu_insumo_sgu_tipoInsumo1`
    FOREIGN KEY (`tipoInsumo`)
    REFERENCES `sgu_tipoInsumo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_servicio` ;

CREATE TABLE IF NOT EXISTS `sgu_servicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `servicio` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_actividadRecursoGrupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_actividadRecursoGrupo` ;

CREATE TABLE IF NOT EXISTS `sgu_actividadRecursoGrupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `idactividadesGrupo` INT NOT NULL,
  `idinsumo` INT NULL,
  `idrepuesto` INT NULL,
  `idservicio` INT NULL,
  `idunidad` INT NOT NULL,
  `detalle` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_actividadRecursoGrupo_sgu_actividadesGrupo1_idx` (`idactividadesGrupo` ASC),
  INDEX `fk_sgu_actividadRecursoGrupo_sgu_insumo1_idx` (`idinsumo` ASC),
  INDEX `fk_sgu_actividadRecursoGrupo_sgu_repuesto1_idx` (`idrepuesto` ASC),
  INDEX `fk_sgu_actividadRecursoGrupo_sgu_unidad1_idx` (`idunidad` ASC),
  INDEX `fk_sgu_actividadRecursoGrupo_sgu_servicio1_idx` (`idservicio` ASC),
  CONSTRAINT `fk_sgu_actividadRecursoGrupo_sgu_actividadesGrupo1`
    FOREIGN KEY (`idactividadesGrupo`)
    REFERENCES `sgu_actividadesGrupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_actividadRecursoGrupo_sgu_insumo1`
    FOREIGN KEY (`idinsumo`)
    REFERENCES `sgu_insumo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_actividadRecursoGrupo_sgu_repuesto1`
    FOREIGN KEY (`idrepuesto`)
    REFERENCES `sgu_repuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_actividadRecursoGrupo_sgu_unidad1`
    FOREIGN KEY (`idunidad`)
    REFERENCES `sgu_unidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_actividadRecursoGrupo_sgu_servicio1`
    FOREIGN KEY (`idservicio`)
    REFERENCES `sgu_servicio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_proveedor` ;

CREATE TABLE IF NOT EXISTS `sgu_proveedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `RIF` VARCHAR(15) NOT NULL,
  `direccion` VARCHAR(80) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_actividadRecurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_actividadRecurso` ;

CREATE TABLE IF NOT EXISTS `sgu_actividadRecurso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `idactividades` INT NOT NULL,
  `idinsumo` INT NULL,
  `idrepuesto` INT NULL,
  `idservicio` INT NULL,
  `idunidad` INT NOT NULL,
  `detalle` VARCHAR(100) NULL,
  `idactividadRecursoGrupo` INT NULL,
  `costoUnitario` FLOAT NOT NULL DEFAULT 0,
  `costoTotal` FLOAT NOT NULL DEFAULT 0,
  `garantia` INT NULL,
  `idtiempoGarantia` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_actividadRecurso_sgu_actividades1_idx` (`idactividades` ASC),
  INDEX `fk_sgu_actividadRecurso_sgu_insumo1_idx` (`idinsumo` ASC),
  INDEX `fk_sgu_actividadRecurso_sgu_repuesto1_idx` (`idrepuesto` ASC),
  INDEX `fk_sgu_actividadRecurso_sgu_unidad1_idx` (`idunidad` ASC),
  INDEX `fk_sgu_actividadRecurso_sgu_actividadRecursoGrupo1_idx` (`idactividadRecursoGrupo` ASC),
  INDEX `fk_sgu_actividadRecurso_sgu_servicio1_idx` (`idservicio` ASC),
  INDEX `fk_sgu_actividadRecurso_sgu_tiempo1_idx` (`idtiempoGarantia` ASC),
  CONSTRAINT `fk_sgu_actividadRecurso_sgu_actividades1`
    FOREIGN KEY (`idactividades`)
    REFERENCES `sgu_actividades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_actividadRecurso_sgu_insumo1`
    FOREIGN KEY (`idinsumo`)
    REFERENCES `sgu_insumo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_actividadRecurso_sgu_repuesto1`
    FOREIGN KEY (`idrepuesto`)
    REFERENCES `sgu_repuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_actividadRecurso_sgu_unidad1`
    FOREIGN KEY (`idunidad`)
    REFERENCES `sgu_unidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_actividadRecurso_sgu_actividadRecursoGrupo1`
    FOREIGN KEY (`idactividadRecursoGrupo`)
    REFERENCES `sgu_actividadRecursoGrupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_actividadRecurso_sgu_servicio1`
    FOREIGN KEY (`idservicio`)
    REFERENCES `sgu_servicio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_actividadRecurso_sgu_tiempo1`
    FOREIGN KEY (`idtiempoGarantia`)
    REFERENCES `sgu_tiempo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_tipoEmpleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_tipoEmpleado` ;

CREATE TABLE IF NOT EXISTS `sgu_tipoEmpleado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_empleado` ;

CREATE TABLE IF NOT EXISTS `sgu_empleado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `cedula` INT NOT NULL,
  `idtipoEmpleado` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_empleado_sgu_tipoEmpleado1_idx` (`idtipoEmpleado` ASC),
  CONSTRAINT `fk_sgu_empleado_sgu_tipoEmpleado1`
    FOREIGN KEY (`idtipoEmpleado`)
    REFERENCES `sgu_tipoEmpleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_ordenMtto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_ordenMtto` ;

CREATE TABLE IF NOT EXISTS `sgu_ordenMtto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `tipo` INT NOT NULL,
  `idestatus` INT NOT NULL,
  `taller` INT NOT NULL,
  `cOperativo` INT NOT NULL,
  `cTaller` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_ordenMtto_sgu_estatus1_idx` (`idestatus` ASC),
  INDEX `fk_sgu_ordenMtto_sgu_proveedor1_idx` (`taller` ASC),
  INDEX `fk_sgu_ordenMtto_sgu_empleado1_idx` (`cOperativo` ASC),
  INDEX `fk_sgu_ordenMtto_sgu_empleado2_idx` (`cTaller` ASC),
  CONSTRAINT `fk_sgu_ordenMtto_sgu_estatus1`
    FOREIGN KEY (`idestatus`)
    REFERENCES `sgu_estatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_ordenMtto_sgu_proveedor1`
    FOREIGN KEY (`taller`)
    REFERENCES `sgu_proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_ordenMtto_sgu_empleado1`
    FOREIGN KEY (`cOperativo`)
    REFERENCES `sgu_empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_ordenMtto_sgu_empleado2`
    FOREIGN KEY (`cTaller`)
    REFERENCES `sgu_empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_detalleOrden`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_detalleOrden` ;

CREATE TABLE IF NOT EXISTS `sgu_detalleOrden` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idordenMtto` INT NOT NULL,
  `idactividades` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_detalleOrden_sgu_ordenMtto1_idx` (`idordenMtto` ASC),
  INDEX `fk_sgu_detalleOrden_sgu_actividades1_idx` (`idactividades` ASC),
  CONSTRAINT `fk_sgu_detalleOrden_sgu_ordenMtto1`
    FOREIGN KEY (`idordenMtto`)
    REFERENCES `sgu_ordenMtto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sgu_detalleOrden_sgu_actividades1`
    FOREIGN KEY (`idactividades`)
    REFERENCES `sgu_actividades` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_factura` ;

CREATE TABLE IF NOT EXISTS `sgu_factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fechaFactura` DATE NOT NULL,
  `codigo` INT NOT NULL,
  `idproveedor` INT NOT NULL,
  `idordenMtto` INT NOT NULL,
  `total` FLOAT NOT NULL DEFAULT 0,
  `iva` FLOAT NOT NULL DEFAULT 0,
  `totalFactura` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_factura_sgu_proveedor1_idx` (`idproveedor` ASC),
  INDEX `fk_sgu_factura_sgu_ordenMtto1_idx` (`idordenMtto` ASC),
  CONSTRAINT `fk_sgu_factura_sgu_proveedor1`
    FOREIGN KEY (`idproveedor`)
    REFERENCES `sgu_proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_factura_sgu_ordenMtto1`
    FOREIGN KEY (`idordenMtto`)
    REFERENCES `sgu_ordenMtto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_facturaAct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_facturaAct` ;

CREATE TABLE IF NOT EXISTS `sgu_facturaAct` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idfactura` INT NOT NULL,
  `iddetalleOrden` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_facturaAct_sgu_factura1_idx` (`idfactura` ASC),
  INDEX `fk_sgu_facturaAct_sgu_detalleOrden1_idx` (`iddetalleOrden` ASC),
  CONSTRAINT `fk_sgu_facturaAct_sgu_factura1`
    FOREIGN KEY (`idfactura`)
    REFERENCES `sgu_factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_facturaAct_sgu_detalleOrden1`
    FOREIGN KEY (`iddetalleOrden`)
    REFERENCES `sgu_detalleOrden` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_estados` ;

CREATE TABLE IF NOT EXISTS `sgu_estados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `estado_UNIQUE` (`estado` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_lugar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_lugar` ;

CREATE TABLE IF NOT EXISTS `sgu_lugar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lugar` VARCHAR(45) NOT NULL,
  `idestados` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_lugar_sgu_estados1_idx` (`idestados` ASC),
  CONSTRAINT `fk_sgu_lugar_sgu_estados1`
    FOREIGN KEY (`idestados`)
    REFERENCES `sgu_estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_tipoViaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_tipoViaje` ;

CREATE TABLE IF NOT EXISTS `sgu_tipoViaje` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_viaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_viaje` ;

CREATE TABLE IF NOT EXISTS `sgu_viaje` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `distanciaKm` FLOAT NOT NULL,
  `idOrigen` INT NOT NULL,
  `idDestino` INT NOT NULL,
  `idtipo` INT NOT NULL,
  `viaje` VARCHAR(80) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_viaje_sgu_lugar1_idx` (`idOrigen` ASC),
  INDEX `fk_sgu_viaje_sgu_lugar2_idx` (`idDestino` ASC),
  INDEX `fk_sgu_viaje_sgu_tipo1_idx` (`idtipo` ASC),
  CONSTRAINT `fk_sgu_viaje_sgu_lugar1`
    FOREIGN KEY (`idOrigen`)
    REFERENCES `sgu_lugar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_viaje_sgu_lugar2`
    FOREIGN KEY (`idDestino`)
    REFERENCES `sgu_lugar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_viaje_sgu_tipo1`
    FOREIGN KEY (`idtipo`)
    REFERENCES `sgu_tipoViaje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_historicoViajes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_historicoViajes` ;

CREATE TABLE IF NOT EXISTS `sgu_historicoViajes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `horaSalida` TIME NOT NULL,
  `horaLlegada` TIME NOT NULL,
  `idviaje` INT NOT NULL,
  `idvehiculo` INT NOT NULL,
  `nroPersonas` INT NOT NULL,
  `idconductor` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_historicoViajes_sgu_viaje1_idx` (`idviaje` ASC),
  INDEX `fk_sgu_historicoViajes_sgu_vehiculo1_idx` (`idvehiculo` ASC),
  UNIQUE INDEX `unico_historico` (`fecha` ASC, `horaSalida` ASC, `horaLlegada` ASC, `idviaje` ASC, `idvehiculo` ASC, `nroPersonas` ASC, `idconductor` ASC),
  INDEX `fk_sgu_historicoViajes_sgu_empleado1_idx` (`idconductor` ASC),
  CONSTRAINT `fk_sgu_historicoViajes_sgu_viaje1`
    FOREIGN KEY (`idviaje`)
    REFERENCES `sgu_viaje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_historicoViajes_sgu_vehiculo1`
    FOREIGN KEY (`idvehiculo`)
    REFERENCES `sgu_vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_historicoViajes_sgu_empleado1`
    FOREIGN KEY (`idconductor`)
    REFERENCES `sgu_empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_kilometraje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_kilometraje` ;

CREATE TABLE IF NOT EXISTS `sgu_kilometraje` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `lectura` INT NOT NULL,
  `idvehiculo` INT NOT NULL,
  `idhistoricoViajes` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_kilometraje_sgu_vehiculo1_idx` (`idvehiculo` ASC),
  INDEX `fk_sgu_kilometraje_sgu_historicoViajes1_idx` (`idhistoricoViajes` ASC),
  CONSTRAINT `fk_sgu_kilometraje_sgu_vehiculo1`
    FOREIGN KEY (`idvehiculo`)
    REFERENCES `sgu_vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_kilometraje_sgu_historicoViajes1`
    FOREIGN KEY (`idhistoricoViajes`)
    REFERENCES `sgu_historicoViajes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_historicoEmpleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_historicoEmpleados` ;

CREATE TABLE IF NOT EXISTS `sgu_historicoEmpleados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NULL,
  `idempleado` INT NOT NULL,
  `idvehiculo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_historicoEmpleados_sgu_empleado1_idx` (`idempleado` ASC),
  INDEX `fk_sgu_historicoEmpleados_sgu_vehiculo1_idx` (`idvehiculo` ASC),
  CONSTRAINT `fk_sgu_historicoEmpleados_sgu_empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `sgu_empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_historicoEmpleados_sgu_vehiculo1`
    FOREIGN KEY (`idvehiculo`)
    REFERENCES `sgu_vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_falla`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_falla` ;

CREATE TABLE IF NOT EXISTS `sgu_falla` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `falla` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_reporteFalla`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_reporteFalla` ;

CREATE TABLE IF NOT EXISTS `sgu_reporteFalla` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(150) NULL,
  `fechaFalla` DATE NOT NULL,
  `fechaRealizada` DATE NOT NULL DEFAULT '0000-01-01',
  `kmRealizada` INT NOT NULL DEFAULT -1,
  `diasParo` INT NOT NULL DEFAULT 0,
  `idtiempo` INT NOT NULL DEFAULT 1,
  `idvehiculo` INT NOT NULL,
  `idempleado` INT NOT NULL,
  `idfalla` INT NOT NULL,
  `idestatus` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_reporteFalla_sgu_vehiculo1_idx` (`idvehiculo` ASC),
  INDEX `fk_sgu_reporteFalla_sgu_empleado1_idx` (`idempleado` ASC),
  INDEX `fk_sgu_reporteFalla_sgu_falla1_idx` (`idfalla` ASC),
  INDEX `fk_sgu_reporteFalla_sgu_tiempo1_idx` (`idtiempo` ASC),
  INDEX `fk_sgu_reporteFalla_sgu_estatus1_idx` (`idestatus` ASC),
  CONSTRAINT `fk_sgu_reporteFalla_sgu_vehiculo1`
    FOREIGN KEY (`idvehiculo`)
    REFERENCES `sgu_vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_reporteFalla_sgu_empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `sgu_empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_reporteFalla_sgu_falla1`
    FOREIGN KEY (`idfalla`)
    REFERENCES `sgu_falla` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_reporteFalla_sgu_tiempo1`
    FOREIGN KEY (`idtiempo`)
    REFERENCES `sgu_tiempo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_reporteFalla_sgu_estatus1`
    FOREIGN KEY (`idestatus`)
    REFERENCES `sgu_estatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_detalleOrdenCo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_detalleOrdenCo` ;

CREATE TABLE IF NOT EXISTS `sgu_detalleOrdenCo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idordenMtto` INT NOT NULL,
  `idreporteFalla` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_detalleOrdenCo_sgu_ordenMtto1_idx` (`idordenMtto` ASC),
  INDEX `fk_sgu_detalleOrdenCo_sgu_reporteFalla1_idx` (`idreporteFalla` ASC),
  CONSTRAINT `fk_sgu_detalleOrdenCo_sgu_ordenMtto1`
    FOREIGN KEY (`idordenMtto`)
    REFERENCES `sgu_ordenMtto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_detalleOrdenCo_sgu_reporteFalla1`
    FOREIGN KEY (`idreporteFalla`)
    REFERENCES `sgu_reporteFalla` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_recursoFalla`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_recursoFalla` ;

CREATE TABLE IF NOT EXISTS `sgu_recursoFalla` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `costoUnitario` FLOAT NOT NULL DEFAULT 0,
  `costoTotal` FLOAT NOT NULL DEFAULT 0,
  `idinsumo` INT NULL,
  `idservicio` INT NULL,
  `idrepuesto` INT NULL,
  `idreporteFalla` INT NOT NULL,
  `idunidad` INT NOT NULL,
  `garantia` INT NULL,
  `idtiempo` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_recursoFalla_sgu_reporteFalla1_idx` (`idreporteFalla` ASC),
  INDEX `fk_sgu_recursoFalla_sgu_unidad1_idx` (`idunidad` ASC),
  INDEX `fk_sgu_recursoFalla_sgu_insumo1_idx` (`idinsumo` ASC),
  INDEX `fk_sgu_recursoFalla_sgu_servicio1_idx` (`idservicio` ASC),
  INDEX `fk_sgu_recursoFalla_sgu_repuesto1_idx` (`idrepuesto` ASC),
  INDEX `fk_sgu_recursoFalla_sgu_tiempo1_idx` (`idtiempo` ASC),
  CONSTRAINT `fk_sgu_recursoFalla_sgu_reporteFalla1`
    FOREIGN KEY (`idreporteFalla`)
    REFERENCES `sgu_reporteFalla` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_recursoFalla_sgu_unidad1`
    FOREIGN KEY (`idunidad`)
    REFERENCES `sgu_unidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_recursoFalla_sgu_insumo1`
    FOREIGN KEY (`idinsumo`)
    REFERENCES `sgu_insumo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_recursoFalla_sgu_servicio1`
    FOREIGN KEY (`idservicio`)
    REFERENCES `sgu_servicio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_recursoFalla_sgu_repuesto1`
    FOREIGN KEY (`idrepuesto`)
    REFERENCES `sgu_repuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_recursoFalla_sgu_tiempo1`
    FOREIGN KEY (`idtiempo`)
    REFERENCES `sgu_tiempo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_estacionServicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_estacionServicio` ;

CREATE TABLE IF NOT EXISTS `sgu_estacionServicio` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_combust`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_combust` ;

CREATE TABLE IF NOT EXISTS `sgu_combust` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `costoLitro` FLOAT NOT NULL,
  `idtipoCombustible` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_combust_sgu_tipoCombustible1_idx` (`idtipoCombustible` ASC),
  CONSTRAINT `fk_sgu_combust_sgu_tipoCombustible1`
    FOREIGN KEY (`idtipoCombustible`)
    REFERENCES `sgu_tipoCombustible` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_historicoCombustible`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_historicoCombustible` ;

CREATE TABLE IF NOT EXISTS `sgu_historicoCombustible` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `litros` FLOAT NOT NULL,
  `costoTotal` FLOAT NOT NULL,
  `idestacionServicio` INT NOT NULL,
  `idconductor` INT NOT NULL,
  `idvehiculo` INT NOT NULL,
  `historico` INT NOT NULL,
  `idcombust` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_historicoCombustible_sgu_vehiculo1_idx` (`idvehiculo` ASC),
  INDEX `fk_sgu_historicoCombustible_sgu_empleado1_idx` (`idconductor` ASC),
  INDEX `fk_sgu_historicoCombustible_sgu_estacionServicio1_idx` (`idestacionServicio` ASC),
  INDEX `fk_sgu_historicoCombustible_sgu_combust1_idx` (`idcombust` ASC),
  CONSTRAINT `fk_sgu_historicoCombustible_sgu_vehiculo1`
    FOREIGN KEY (`idvehiculo`)
    REFERENCES `sgu_vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_historicoCombustible_sgu_empleado1`
    FOREIGN KEY (`idconductor`)
    REFERENCES `sgu_empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_historicoCombustible_sgu_estacionServicio1`
    FOREIGN KEY (`idestacionServicio`)
    REFERENCES `sgu_estacionServicio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_historicoCombustible_sgu_combust1`
    FOREIGN KEY (`idcombust`)
    REFERENCES `sgu_combust` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_chasis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_chasis` ;

CREATE TABLE IF NOT EXISTS `sgu_chasis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `nroEjes` INT NOT NULL,
  `cantidadNormales` INT NOT NULL,
  `cantidadRepuesto` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_posicionEje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_posicionEje` ;

CREATE TABLE IF NOT EXISTS `sgu_posicionEje` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `posicionEje` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_detalleEje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_detalleEje` ;

CREATE TABLE IF NOT EXISTS `sgu_detalleEje` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nroRuedas` INT NOT NULL,
  `idchasis` INT NOT NULL,
  `idposicionEje` INT NOT NULL,
  `nombre` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_detalleEje_sgu_chasis1_idx` (`idchasis` ASC),
  INDEX `fk_sgu_detalleEje_sgu_posicionEje1_idx` (`idposicionEje` ASC),
  CONSTRAINT `fk_sgu_detalleEje_sgu_chasis1`
    FOREIGN KEY (`idchasis`)
    REFERENCES `sgu_chasis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_detalleEje_sgu_posicionEje1`
    FOREIGN KEY (`idposicionEje`)
    REFERENCES `sgu_posicionEje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_posicionRueda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_posicionRueda` ;

CREATE TABLE IF NOT EXISTS `sgu_posicionRueda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `posicionRueda` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_estatusCaucho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_estatusCaucho` ;

CREATE TABLE IF NOT EXISTS `sgu_estatusCaucho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estatusCaucho` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_detalleRueda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_detalleRueda` ;

CREATE TABLE IF NOT EXISTS `sgu_detalleRueda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idposicionRueda` INT NOT NULL,
  `iddetalleEje` INT NOT NULL,
  `idcaucho` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_detalleRueda_sgu_posicionRueda1_idx` (`idposicionRueda` ASC),
  INDEX `fk_sgu_detalleRueda_sgu_detalleEje1_idx` (`iddetalleEje` ASC),
  INDEX `fk_sgu_detalleRueda_sgu_caucho1_idx` (`idcaucho` ASC),
  CONSTRAINT `fk_sgu_detalleRueda_sgu_posicionRueda1`
    FOREIGN KEY (`idposicionRueda`)
    REFERENCES `sgu_posicionRueda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_detalleRueda_sgu_detalleEje1`
    FOREIGN KEY (`iddetalleEje`)
    REFERENCES `sgu_detalleEje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_detalleRueda_sgu_caucho1`
    FOREIGN KEY (`idcaucho`)
    REFERENCES `sgu_caucho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_asigChasis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_asigChasis` ;

CREATE TABLE IF NOT EXISTS `sgu_asigChasis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idchasis` INT NOT NULL,
  `idgrupo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_asigChasis_sgu_chasis1_idx` (`idchasis` ASC),
  INDEX `fk_sgu_asigChasis_sgu_grupo1_idx` (`idgrupo` ASC),
  CONSTRAINT `fk_sgu_asigChasis_sgu_chasis1`
    FOREIGN KEY (`idchasis`)
    REFERENCES `sgu_chasis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_asigChasis_sgu_grupo1`
    FOREIGN KEY (`idgrupo`)
    REFERENCES `sgu_grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_historicoCaucho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_historicoCaucho` ;

CREATE TABLE IF NOT EXISTS `sgu_historicoCaucho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL DEFAULT '0000-01-01',
  `serial` VARCHAR(45) NOT NULL DEFAULT 0,
  `idestatusCaucho` INT NOT NULL,
  `idcaucho` INT NOT NULL,
  `idmarcaCaucho` INT NULL,
  `idvehiculo` INT NOT NULL,
  `iddetalleRueda` INT NULL,
  `idasigChasis` INT NOT NULL,
  `costounitario` FLOAT NOT NULL DEFAULT 0,
  `costoTotal` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_historicoCaucho_sgu_estatusCaucho1_idx` (`idestatusCaucho` ASC),
  INDEX `fk_sgu_historicoCaucho_sgu_caucho1_idx` (`idcaucho` ASC),
  INDEX `fk_sgu_historicoCaucho_sgu_marcaCaucho1_idx` (`idmarcaCaucho` ASC),
  INDEX `fk_sgu_historicoCaucho_sgu_vehiculo1_idx` (`idvehiculo` ASC),
  INDEX `fk_sgu_historicoCaucho_sgu_detalleRueda1_idx` (`iddetalleRueda` ASC),
  INDEX `fk_sgu_historicoCaucho_sgu_asigChasis1_idx` (`idasigChasis` ASC),
  CONSTRAINT `fk_sgu_historicoCaucho_sgu_estatusCaucho1`
    FOREIGN KEY (`idestatusCaucho`)
    REFERENCES `sgu_estatusCaucho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_historicoCaucho_sgu_caucho1`
    FOREIGN KEY (`idcaucho`)
    REFERENCES `sgu_caucho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_historicoCaucho_sgu_marcaCaucho1`
    FOREIGN KEY (`idmarcaCaucho`)
    REFERENCES `sgu_marcaCaucho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_historicoCaucho_sgu_vehiculo1`
    FOREIGN KEY (`idvehiculo`)
    REFERENCES `sgu_vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_historicoCaucho_sgu_detalleRueda1`
    FOREIGN KEY (`iddetalleRueda`)
    REFERENCES `sgu_detalleRueda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_historicoCaucho_sgu_asigChasis1`
    FOREIGN KEY (`idasigChasis`)
    REFERENCES `sgu_asigChasis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_cauchoRep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_cauchoRep` ;

CREATE TABLE IF NOT EXISTS `sgu_cauchoRep` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idchasis` INT NOT NULL,
  `idcaucho` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_cauchoRep_sgu_chasis1_idx` (`idchasis` ASC),
  INDEX `fk_sgu_cauchoRep_sgu_caucho1_idx` (`idcaucho` ASC),
  CONSTRAINT `fk_sgu_cauchoRep_sgu_chasis1`
    FOREIGN KEY (`idchasis`)
    REFERENCES `sgu_chasis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_cauchoRep_sgu_caucho1`
    FOREIGN KEY (`idcaucho`)
    REFERENCES `sgu_caucho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_fallaCaucho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_fallaCaucho` ;

CREATE TABLE IF NOT EXISTS `sgu_fallaCaucho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `falla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_accionCaucho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_accionCaucho` ;

CREATE TABLE IF NOT EXISTS `sgu_accionCaucho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `accion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_detalleEventoCa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_detalleEventoCa` ;

CREATE TABLE IF NOT EXISTS `sgu_detalleEventoCa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fechaFalla` DATE NOT NULL,
  `fechaRealizada` DATE NOT NULL,
  `comentario` VARCHAR(100) NULL,
  `idhistoricoCaucho` INT NOT NULL,
  `idfallaCaucho` INT NULL,
  `idestatus` INT NOT NULL,
  `idempleado` INT NULL,
  `idaccionCaucho` INT NOT NULL,
  `posicionOrigen` INT NULL,
  `cauchoOrigen` INT NULL,
  `posicionDestino` INT NULL,
  `cauchoDestino` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_detalleFallaCa_sgu_historicoCaucho1_idx` (`idhistoricoCaucho` ASC),
  INDEX `fk_sgu_detalleFallaCa_sgu_fallaCaucho1_idx` (`idfallaCaucho` ASC),
  INDEX `fk_sgu_detalleEventoCa_sgu_estatus1_idx` (`idestatus` ASC),
  INDEX `fk_sgu_detalleEventoCa_sgu_empleado1_idx` (`idempleado` ASC),
  INDEX `fk_sgu_detalleEventoCa_sgu_accionCaucho1_idx` (`idaccionCaucho` ASC),
  INDEX `fk_sgu_detalleEventoCa_sgu_detalleRueda1_idx` (`posicionOrigen` ASC),
  INDEX `fk_sgu_detalleEventoCa_sgu_detalleRueda2_idx` (`posicionDestino` ASC),
  INDEX `fk_sgu_detalleEventoCa_sgu_historicoCaucho2_idx` (`cauchoOrigen` ASC),
  INDEX `fk_sgu_detalleEventoCa_sgu_historicoCaucho3_idx` (`cauchoDestino` ASC),
  CONSTRAINT `fk_sgu_detalleEventoCa_sgu_historicoCaucho1`
    FOREIGN KEY (`idhistoricoCaucho`)
    REFERENCES `sgu_historicoCaucho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_detalleEventoCa_sgu_fallaCaucho1`
    FOREIGN KEY (`idfallaCaucho`)
    REFERENCES `sgu_fallaCaucho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_detalleEventoCa_sgu_estatus1`
    FOREIGN KEY (`idestatus`)
    REFERENCES `sgu_estatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_detalleEventoCa_sgu_empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `sgu_empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_detalleEventoCa_sgu_accionCaucho1`
    FOREIGN KEY (`idaccionCaucho`)
    REFERENCES `sgu_accionCaucho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_detalleEventoCa_sgu_detalleRueda1`
    FOREIGN KEY (`posicionOrigen`)
    REFERENCES `sgu_detalleRueda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_detalleEventoCa_sgu_detalleRueda2`
    FOREIGN KEY (`posicionDestino`)
    REFERENCES `sgu_detalleRueda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_detalleEventoCa_sgu_historicoCaucho2`
    FOREIGN KEY (`cauchoOrigen`)
    REFERENCES `sgu_historicoCaucho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_detalleEventoCa_sgu_historicoCaucho3`
    FOREIGN KEY (`cauchoDestino`)
    REFERENCES `sgu_historicoCaucho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_detOrdNeumatico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_detOrdNeumatico` ;

CREATE TABLE IF NOT EXISTS `sgu_detOrdNeumatico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idordenMtto` INT NOT NULL,
  `iddetalleEventoCa` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_detOrdNeumatico_sgu_ordenMtto1_idx` (`idordenMtto` ASC),
  INDEX `fk_sgu_detOrdNeumatico_sgu_detalleFallaCa1_idx` (`iddetalleEventoCa` ASC),
  CONSTRAINT `fk_sgu_detOrdNeumatico_sgu_ordenMtto1`
    FOREIGN KEY (`idordenMtto`)
    REFERENCES `sgu_ordenMtto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_detOrdNeumatico_sgu_detalleEventoCa1`
    FOREIGN KEY (`iddetalleEventoCa`)
    REFERENCES `sgu_detalleEventoCa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_recursoCaucho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_recursoCaucho` ;

CREATE TABLE IF NOT EXISTS `sgu_recursoCaucho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `recurso` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgu_detRecCaucho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgu_detRecCaucho` ;

CREATE TABLE IF NOT EXISTS `sgu_detRecCaucho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `costoUnitario` FLOAT NOT NULL,
  `costoTotal` FLOAT NOT NULL,
  `idrecursoCaucho` INT NOT NULL,
  `idhistoricoCaucho` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sgu_detRecCaucho_sgu_recursoCaucho1_idx` (`idrecursoCaucho` ASC),
  INDEX `fk_sgu_detRecCaucho_sgu_historicoCaucho1_idx` (`idhistoricoCaucho` ASC),
  CONSTRAINT `fk_sgu_detRecCaucho_sgu_recursoCaucho1`
    FOREIGN KEY (`idrecursoCaucho`)
    REFERENCES `sgu_recursoCaucho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sgu_detRecCaucho_sgu_historicoCaucho1`
    FOREIGN KEY (`idhistoricoCaucho`)
    REFERENCES `sgu_historicoCaucho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `sgu_marca`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_marca` (`id`, `marca`) VALUES (1, 'Chevrolet');
INSERT INTO `sgu_marca` (`id`, `marca`) VALUES (2, 'Kawasaki');
INSERT INTO `sgu_marca` (`id`, `marca`) VALUES (3, 'Toyota');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_modelo`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_modelo` (`id`, `modelo`, `idmarca`) VALUES (1, 'Aveo', 1);
INSERT INTO `sgu_modelo` (`id`, `modelo`, `idmarca`) VALUES (2, 'KLR', 2);
INSERT INTO `sgu_modelo` (`id`, `modelo`, `idmarca`) VALUES (3, 'Corolla', 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_tipo`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_tipo` (`id`, `tipo`) VALUES (1, 'Autobus');
INSERT INTO `sgu_tipo` (`id`, `tipo`) VALUES (2, 'Moto');
INSERT INTO `sgu_tipo` (`id`, `tipo`) VALUES (3, 'Automovil');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_grupo`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_grupo` (`id`, `grupo`, `descripcion`, `idtipo`) VALUES (1, 'Aveo 2012 A/AC', 'autos aveos ', 3);
INSERT INTO `sgu_grupo` (`id`, `grupo`, `descripcion`, `idtipo`) VALUES (2, 'KLR 2014 650cc', 'motos klr ', 2);
INSERT INTO `sgu_grupo` (`id`, `grupo`, `descripcion`, `idtipo`) VALUES (3, 'Encava E912 2001', 'encavas 2001', 1);
INSERT INTO `sgu_grupo` (`id`, `grupo`, `descripcion`, `idtipo`) VALUES (4, 'Corolla 2001 S/AC', 'toyotas corolla 2001 sincrónicos con a/c', 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_color`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_color` (`id`, `color`) VALUES (1, 'Amarillo');
INSERT INTO `sgu_color` (`id`, `color`) VALUES (2, 'Azul');
INSERT INTO `sgu_color` (`id`, `color`) VALUES (3, 'Blanco');
INSERT INTO `sgu_color` (`id`, `color`) VALUES (4, 'Naranja');
INSERT INTO `sgu_color` (`id`, `color`) VALUES (5, 'Rojo');
INSERT INTO `sgu_color` (`id`, `color`) VALUES (6, 'Verde');
INSERT INTO `sgu_color` (`id`, `color`) VALUES (7, 'Negro');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_propiedad`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_propiedad` (`id`, `propiedad`) VALUES (1, 'UNET');
INSERT INTO `sgu_propiedad` (`id`, `propiedad`) VALUES (2, 'Decanato de investigación');
INSERT INTO `sgu_propiedad` (`id`, `propiedad`) VALUES (3, 'SIRCA');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_tipoCombustible`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_tipoCombustible` (`id`, `combustible`) VALUES (1, 'Gasolina');
INSERT INTO `sgu_tipoCombustible` (`id`, `combustible`) VALUES (2, 'Diesel');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_vehiculo`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_vehiculo` (`id`, `numeroUnidad`, `serialCarroceria`, `serialMotor`, `placa`, `anno`, `nroPuestos`, `nroEjes`, `capCarga`, `comentario`, `cantidadRuedas`, `capTanque`, `idmodelo`, `idgrupo`, `idcolor`, `idpropiedad`, `idcombustible`, `fechaRegistro`, `KmInicial`, `rendimiento`) VALUES (1, 1, '6V57932453GV', '634656953', 'PAA24V', 2006, 50, 2, 5000, NULL, 6, 250, 1, 1, 1, 1, 1, NULL, 90000, 10);
INSERT INTO `sgu_vehiculo` (`id`, `numeroUnidad`, `serialCarroceria`, `serialMotor`, `placa`, `anno`, `nroPuestos`, `nroEjes`, `capCarga`, `comentario`, `cantidadRuedas`, `capTanque`, `idmodelo`, `idgrupo`, `idcolor`, `idpropiedad`, `idcombustible`, `fechaRegistro`, `KmInicial`, `rendimiento`) VALUES (2, 2, 'F54959495', '456789678', 'AB232GS', 2009, 5, 2, 500, NULL, 4, 45, 2, 2, 2, 2, 1, NULL, 120000, 9);
INSERT INTO `sgu_vehiculo` (`id`, `numeroUnidad`, `serialCarroceria`, `serialMotor`, `placa`, `anno`, `nroPuestos`, `nroEjes`, `capCarga`, `comentario`, `cantidadRuedas`, `capTanque`, `idmodelo`, `idgrupo`, `idcolor`, `idpropiedad`, `idcombustible`, `fechaRegistro`, `KmInicial`, `rendimiento`) VALUES (3, 3, '6FHEF4467', '789234545', 'AF453FT', 2012, 2, 1, 150, NULL, 2, 15, 3, 3, 1, 1, 2, NULL, 30000, 12);
INSERT INTO `sgu_vehiculo` (`id`, `numeroUnidad`, `serialCarroceria`, `serialMotor`, `placa`, `anno`, `nroPuestos`, `nroEjes`, `capCarga`, `comentario`, `cantidadRuedas`, `capTanque`, `idmodelo`, `idgrupo`, `idcolor`, `idpropiedad`, `idcombustible`, `fechaRegistro`, `KmInicial`, `rendimiento`) VALUES (4, 4, 'HZ1345GFT54', '634238998', 'AB546NJ', 2010, 5, 2, 500, NULL, 4, 50, 3, 3, 3, 3, 1, NULL, 45000, 12);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_TipoRepuesto`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_TipoRepuesto` (`id`, `tipo`) VALUES (1, 'Mecánico');
INSERT INTO `sgu_TipoRepuesto` (`id`, `tipo`) VALUES (2, 'Eléctrico');
INSERT INTO `sgu_TipoRepuesto` (`id`, `tipo`) VALUES (3, 'Físico');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_subTipoRepuesto`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_subTipoRepuesto` (`id`, `idTipoRepuesto`, `subTipo`) VALUES (1, 1, 'Aire acondicionado');
INSERT INTO `sgu_subTipoRepuesto` (`id`, `idTipoRepuesto`, `subTipo`) VALUES (2, 1, 'Caja sincrónica');
INSERT INTO `sgu_subTipoRepuesto` (`id`, `idTipoRepuesto`, `subTipo`) VALUES (3, 1, 'Enfriamiento');
INSERT INTO `sgu_subTipoRepuesto` (`id`, `idTipoRepuesto`, `subTipo`) VALUES (4, 1, 'Frenos');
INSERT INTO `sgu_subTipoRepuesto` (`id`, `idTipoRepuesto`, `subTipo`) VALUES (5, 1, 'Kit clutch');
INSERT INTO `sgu_subTipoRepuesto` (`id`, `idTipoRepuesto`, `subTipo`) VALUES (6, 1, 'Motor');
INSERT INTO `sgu_subTipoRepuesto` (`id`, `idTipoRepuesto`, `subTipo`) VALUES (7, 1, 'Transmisión');
INSERT INTO `sgu_subTipoRepuesto` (`id`, `idTipoRepuesto`, `subTipo`) VALUES (8, 1, 'Tren delantero');
INSERT INTO `sgu_subTipoRepuesto` (`id`, `idTipoRepuesto`, `subTipo`) VALUES (9, 2, 'Sistema eléctrico');
INSERT INTO `sgu_subTipoRepuesto` (`id`, `idTipoRepuesto`, `subTipo`) VALUES (10, 2, 'Sensores y actuadores');
INSERT INTO `sgu_subTipoRepuesto` (`id`, `idTipoRepuesto`, `subTipo`) VALUES (11, 3, 'Carrocería');
INSERT INTO `sgu_subTipoRepuesto` (`id`, `idTipoRepuesto`, `subTipo`) VALUES (12, 3, 'Escape');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_unidad`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_unidad` (`id`, `unidad`, `corto`) VALUES (1, 'Pieza(s)', 'Pza(s)');
INSERT INTO `sgu_unidad` (`id`, `unidad`, `corto`) VALUES (2, 'Kit', 'Kit');
INSERT INTO `sgu_unidad` (`id`, `unidad`, `corto`) VALUES (3, 'Galón(es)', 'Gal');
INSERT INTO `sgu_unidad` (`id`, `unidad`, `corto`) VALUES (4, 'Litro(s)', 'L');
INSERT INTO `sgu_unidad` (`id`, `unidad`, `corto`) VALUES (5, 'Juego', 'Jgo.');
INSERT INTO `sgu_unidad` (`id`, `unidad`, `corto`) VALUES (6, 'Tubo(s)', 'Tubo(s)');
INSERT INTO `sgu_unidad` (`id`, `unidad`, `corto`) VALUES (7, 'Centímetros cúbicos', 'CC');
INSERT INTO `sgu_unidad` (`id`, `unidad`, `corto`) VALUES (8, 'Servicio', 'Serv.');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_repuesto`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (1, 'Compresor', NULL, 1, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (2, 'Condensador', NULL, 1, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (3, 'Evaporador', NULL, 1, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (5, 'Valvula expanción', NULL, 1, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (6, 'Bronce', NULL, 2, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (7, 'Engranaje', NULL, 2, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (8, 'Rodamiento', NULL, 2, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (9, 'Estopera', NULL, 2, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (11, 'Radiador', NULL, 3, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (12, 'Bomba', NULL, 4, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (13, 'Cilindro', NULL, 4, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (14, 'Pastilla', '1 juego son 4 pastillas para 2 ruedas.', 4, 5);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (15, 'Zapata', NULL, 4, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (16, 'Disco', NULL, 4, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (17, 'Tambor', NULL, 4, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (18, 'Collarin', NULL, 5, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (19, 'Disco', NULL, 5, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (20, 'Plato', NULL, 5, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (21, 'Anillo', NULL, 6, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (22, 'Biela', NULL, 6, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (23, 'Bloque', NULL, 6, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (24, 'Cámara', NULL, 6, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (25, 'Carburador', NULL, 6, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (26, 'Concha', NULL, 6, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (27, 'Multiple de entrada', NULL, 6, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (28, 'Piston', NULL, 6, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (29, 'Taquete', NULL, 6, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (30, 'Válvula', NULL, 6, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (31, 'Cardán', NULL, 7, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (32, 'Corona', NULL, 7, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (33, 'Piñon', NULL, 7, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (34, 'Cruceta', NULL, 7, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (35, 'Satélite', NULL, 7, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (36, 'Planetario', NULL, 7, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (37, 'Rodamiento Pta eje', NULL, 7, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (38, 'Amortiguador', NULL, 8, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (39, 'Brazo axial', NULL, 8, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (40, 'Buje', NULL, 8, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (41, 'Cajetín', NULL, 8, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (43, 'Espiral', NULL, 8, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (44, 'Junta homocinética', NULL, 8, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (45, 'Meseta', NULL, 8, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (46, 'Muñón', NULL, 8, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (47, 'Terminal', NULL, 8, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (48, 'Alternador', NULL, 9, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (49, 'Batería', NULL, 9, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (50, 'Bobina', NULL, 9, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (51, 'Bujía', NULL, 9, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (52, 'Ramal cable', NULL, 9, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (53, 'Cable bujía', NULL, 9, 5);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (54, 'Luces foco', NULL, 9, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (55, 'Bomba combustible', NULL, 10, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (56, 'Unidad de control', NULL, 10, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (57, 'Valvula IAC', NULL, 10, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (58, 'Inyector', NULL, 10, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (59, 'MAF', NULL, 10, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (60, 'TPS', NULL, 10, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (61, 'MAP', NULL, 10, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (62, 'Capot', NULL, 11, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (63, 'Puerta', NULL, 11, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (64, 'Maleta', NULL, 11, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (65, 'Header', NULL, 12, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (67, 'Covertidor catalítico', NULL, 12, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (68, 'Silenciador', NULL, 12, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (69, 'Base', NULL, 6, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (70, 'Parachoques', NULL, 11, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (71, 'Guarda Barro', NULL, 11, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (72, 'Parabrisas', NULL, 11, 1);
INSERT INTO `sgu_repuesto` (`id`, `repuesto`, `descripcion`, `idsubTipoRepuesto`, `idunidad`) VALUES (73, 'Ventana', NULL, 11, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_parametro`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_parametro` (`id`, `nombre`, `valor`, `descripcion`, `fecha`) VALUES (1, 'IVA', '12', 'Impuesto valor agregado', '2014-12-10');
INSERT INTO `sgu_parametro` (`id`, `nombre`, `valor`, `descripcion`, `fecha`) VALUES (2, 'alertaReposicion', '5', 'Días que un vehiculo no ha tenido reposición de combustible', '2014-12-30');
INSERT INTO `sgu_parametro` (`id`, `nombre`, `valor`, `descripcion`, `fecha`) VALUES (3, 'alertaCambioCauchos', '1', 'Tiempo que un neumático no se ha cambiado', '2015-01-15');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_Sinonimo`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_Sinonimo` (`id`, `sinonimo`, `idrepuesto1`, `idrepuesto2`) VALUES (NULL, 'Tacos', 14, NULL);
INSERT INTO `sgu_Sinonimo` (`id`, `sinonimo`, `idrepuesto1`, `idrepuesto2`) VALUES (NULL, 'Bandas', 15, NULL);
INSERT INTO `sgu_Sinonimo` (`id`, `sinonimo`, `idrepuesto1`, `idrepuesto2`) VALUES (NULL, 'Punta de tripoide', 44, NULL);
INSERT INTO `sgu_Sinonimo` (`id`, `sinonimo`, `idrepuesto1`, `idrepuesto2`) VALUES (NULL, 'Pila', 55, NULL);
INSERT INTO `sgu_Sinonimo` (`id`, `sinonimo`, `idrepuesto1`, `idrepuesto2`) VALUES (NULL, 'Computadora', 56, NULL);
INSERT INTO `sgu_Sinonimo` (`id`, `sinonimo`, `idrepuesto1`, `idrepuesto2`) VALUES (NULL, 'Sensor de mínimo', 57, NULL);
INSERT INTO `sgu_Sinonimo` (`id`, `sinonimo`, `idrepuesto1`, `idrepuesto2`) VALUES (NULL, 'Tijeras', 45, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_medidaCaucho`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_medidaCaucho` (`id`, `medida`) VALUES (1, '165/60');
INSERT INTO `sgu_medidaCaucho` (`id`, `medida`) VALUES (2, '175/60');
INSERT INTO `sgu_medidaCaucho` (`id`, `medida`) VALUES (3, '195/80');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_rin`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_rin` (`id`, `rin`) VALUES (1, 13);
INSERT INTO `sgu_rin` (`id`, `rin`) VALUES (2, 14);
INSERT INTO `sgu_rin` (`id`, `rin`) VALUES (3, 15);
INSERT INTO `sgu_rin` (`id`, `rin`) VALUES (4, 16);
INSERT INTO `sgu_rin` (`id`, `rin`) VALUES (5, 17);
INSERT INTO `sgu_rin` (`id`, `rin`) VALUES (6, 18);
INSERT INTO `sgu_rin` (`id`, `rin`) VALUES (7, 19);
INSERT INTO `sgu_rin` (`id`, `rin`) VALUES (8, 20);
INSERT INTO `sgu_rin` (`id`, `rin`) VALUES (9, 21);
INSERT INTO `sgu_rin` (`id`, `rin`) VALUES (10, 22);
INSERT INTO `sgu_rin` (`id`, `rin`) VALUES (11, 23);
INSERT INTO `sgu_rin` (`id`, `rin`) VALUES (12, 24);
INSERT INTO `sgu_rin` (`id`, `rin`) VALUES (13, 25);
INSERT INTO `sgu_rin` (`id`, `rin`) VALUES (14, 26);
INSERT INTO `sgu_rin` (`id`, `rin`) VALUES (15, 27);
INSERT INTO `sgu_rin` (`id`, `rin`) VALUES (16, 28);
INSERT INTO `sgu_rin` (`id`, `rin`) VALUES (17, 29);
INSERT INTO `sgu_rin` (`id`, `rin`) VALUES (18, 30);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_piso`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_piso` (`id`, `piso`) VALUES (1, 'convencional');
INSERT INTO `sgu_piso` (`id`, `piso`) VALUES (2, 'radial');
INSERT INTO `sgu_piso` (`id`, `piso`) VALUES (3, 'tracción');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_caucho`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_caucho` (`id`, `idmedidaCaucho`, `idrin`, `idpiso`) VALUES (1, 1, 1, 1);
INSERT INTO `sgu_caucho` (`id`, `idmedidaCaucho`, `idrin`, `idpiso`) VALUES (2, 2, 2, 2);
INSERT INTO `sgu_caucho` (`id`, `idmedidaCaucho`, `idrin`, `idpiso`) VALUES (3, 3, 3, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_marcaCaucho`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_marcaCaucho` (`id`, `nombre`) VALUES (1, 'Firestone');
INSERT INTO `sgu_marcaCaucho` (`id`, `nombre`) VALUES (2, 'Goodyear');
INSERT INTO `sgu_marcaCaucho` (`id`, `nombre`) VALUES (3, 'Dunlop');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_prioridad`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_prioridad` (`id`, `prioridad`) VALUES (1, 'Baja');
INSERT INTO `sgu_prioridad` (`id`, `prioridad`) VALUES (2, 'Media');
INSERT INTO `sgu_prioridad` (`id`, `prioridad`) VALUES (3, 'Alta');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_tiempo`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_tiempo` (`id`, `tiempo`, `sqlTimevalues`) VALUES (1, 'Día(s)', 'D');
INSERT INTO `sgu_tiempo` (`id`, `tiempo`, `sqlTimevalues`) VALUES (2, 'Hora(s)', 'H');
INSERT INTO `sgu_tiempo` (`id`, `tiempo`, `sqlTimevalues`) VALUES (3, 'Mes(es)', 'M');
INSERT INTO `sgu_tiempo` (`id`, `tiempo`, `sqlTimevalues`) VALUES (4, 'Año(s)', 'Y');
INSERT INTO `sgu_tiempo` (`id`, `tiempo`, `sqlTimevalues`) VALUES (5, 'Minuto(s)', 'i');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_actividadMtto`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_actividadMtto` (`id`, `actividad`) VALUES (1, 'Lavado y engrase');
INSERT INTO `sgu_actividadMtto` (`id`, `actividad`) VALUES (2, 'Cambio de aceite y filtro');
INSERT INTO `sgu_actividadMtto` (`id`, `actividad`) VALUES (3, 'Cambio de correa de los tiempos, polea y tesor');
INSERT INTO `sgu_actividadMtto` (`id`, `actividad`) VALUES (4, 'Cambio de correa de servicios');
INSERT INTO `sgu_actividadMtto` (`id`, `actividad`) VALUES (7, 'Cambio de bujías');
INSERT INTO `sgu_actividadMtto` (`id`, `actividad`) VALUES (8, 'Inspección de bandas poleas y tensores');
INSERT INTO `sgu_actividadMtto` (`id`, `actividad`) VALUES (9, 'Cambio de pastillas');
INSERT INTO `sgu_actividadMtto` (`id`, `actividad`) VALUES (10, 'Cambio de bandas');
INSERT INTO `sgu_actividadMtto` (`id`, `actividad`) VALUES (11, 'Chequeo del nivel de fluidos');
INSERT INTO `sgu_actividadMtto` (`id`, `actividad`) VALUES (17, 'Cambio de clutch (plato disco y collarín)');
INSERT INTO `sgu_actividadMtto` (`id`, `actividad`) VALUES (19, 'Limpieza revisión y ajuste');
INSERT INTO `sgu_actividadMtto` (`id`, `actividad`) VALUES (23, 'Cambio de puntas de tripiode');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_estatus`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_estatus` (`id`, `estatus`) VALUES (1, 'Por definir');
INSERT INTO `sgu_estatus` (`id`, `estatus`) VALUES (2, 'No ejecutada');
INSERT INTO `sgu_estatus` (`id`, `estatus`) VALUES (3, 'Ejecutada');
INSERT INTO `sgu_estatus` (`id`, `estatus`) VALUES (4, 'En progreso');
INSERT INTO `sgu_estatus` (`id`, `estatus`) VALUES (5, 'Abierta');
INSERT INTO `sgu_estatus` (`id`, `estatus`) VALUES (6, 'Lista para cerrar');
INSERT INTO `sgu_estatus` (`id`, `estatus`) VALUES (7, 'Cerrada');
INSERT INTO `sgu_estatus` (`id`, `estatus`) VALUES (8, 'Por atender');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_tipoInsumo`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_tipoInsumo` (`id`, `tipo`) VALUES (1, 'Lubricantes');
INSERT INTO `sgu_tipoInsumo` (`id`, `tipo`) VALUES (2, 'Fluidos');
INSERT INTO `sgu_tipoInsumo` (`id`, `tipo`) VALUES (3, 'Limpieza');
INSERT INTO `sgu_tipoInsumo` (`id`, `tipo`) VALUES (4, 'Autopartes');
INSERT INTO `sgu_tipoInsumo` (`id`, `tipo`) VALUES (5, 'Filtros');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_insumo`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_insumo` (`id`, `insumo`, `tipoInsumo`) VALUES (1, 'Aceite SAE 20W50', 1);
INSERT INTO `sgu_insumo` (`id`, `insumo`, `tipoInsumo`) VALUES (3, 'Aceite hidraulico', 1);
INSERT INTO `sgu_insumo` (`id`, `insumo`, `tipoInsumo`) VALUES (4, 'Aceite multigrado', 1);
INSERT INTO `sgu_insumo` (`id`, `insumo`, `tipoInsumo`) VALUES (5, 'Grasa de alta temperatura', 1);
INSERT INTO `sgu_insumo` (`id`, `insumo`, `tipoInsumo`) VALUES (6, 'Aceite para transmisión manual', 1);
INSERT INTO `sgu_insumo` (`id`, `insumo`, `tipoInsumo`) VALUES (7, 'Motorkote', 1);
INSERT INTO `sgu_insumo` (`id`, `insumo`, `tipoInsumo`) VALUES (2, 'Aceite SAE 15W40', 1);
INSERT INTO `sgu_insumo` (`id`, `insumo`, `tipoInsumo`) VALUES (8, 'Liga de frenos DOT3', 2);
INSERT INTO `sgu_insumo` (`id`, `insumo`, `tipoInsumo`) VALUES (9, 'liga de frenos DOT4', 2);
INSERT INTO `sgu_insumo` (`id`, `insumo`, `tipoInsumo`) VALUES (10, 'Refrigerante', 2);
INSERT INTO `sgu_insumo` (`id`, `insumo`, `tipoInsumo`) VALUES (11, 'Anticongelante', 2);
INSERT INTO `sgu_insumo` (`id`, `insumo`, `tipoInsumo`) VALUES (12, 'Liquido limpiarabrisas', 3);
INSERT INTO `sgu_insumo` (`id`, `insumo`, `tipoInsumo`) VALUES (13, 'Champu para carros', 3);
INSERT INTO `sgu_insumo` (`id`, `insumo`, `tipoInsumo`) VALUES (14, 'Cepillos limpiaparabrisas', 3);
INSERT INTO `sgu_insumo` (`id`, `insumo`, `tipoInsumo`) VALUES (15, 'Filtro de aire', 5);
INSERT INTO `sgu_insumo` (`id`, `insumo`, `tipoInsumo`) VALUES (16, 'Filtro de aceite', 5);
INSERT INTO `sgu_insumo` (`id`, `insumo`, `tipoInsumo`) VALUES (17, 'Filtro de gasolina', 5);
INSERT INTO `sgu_insumo` (`id`, `insumo`, `tipoInsumo`) VALUES (18, 'Filtro de diesel', 5);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_servicio`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_servicio` (`id`, `servicio`) VALUES (1, 'Lavado y engrase');
INSERT INTO `sgu_servicio` (`id`, `servicio`) VALUES (2, 'rectificación pieza');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_proveedor`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_proveedor` (`id`, `nombre`, `RIF`, `direccion`, `telefono`) VALUES (1, 'Rectificadora la concordia', 'J-1932324-1', 'La concordia', '02763478745');
INSERT INTO `sgu_proveedor` (`id`, `nombre`, `RIF`, `direccion`, `telefono`) VALUES (2, 'Autolavado Las vegas', 'J-1232345-5', 'Las vegas Táriba', '02763945257');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_tipoEmpleado`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_tipoEmpleado` (`id`, `tipo`) VALUES (1, 'Conductor');
INSERT INTO `sgu_tipoEmpleado` (`id`, `tipo`) VALUES (2, 'Coordinador operativo');
INSERT INTO `sgu_tipoEmpleado` (`id`, `tipo`) VALUES (3, 'Coordinador de transporte');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_empleado`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_empleado` (`id`, `nombre`, `apellido`, `cedula`, `idtipoEmpleado`) VALUES (1, 'Juan', 'Pérez', 8745856, 1);
INSERT INTO `sgu_empleado` (`id`, `nombre`, `apellido`, `cedula`, `idtipoEmpleado`) VALUES (5, 'Aberto', 'Cárdenas', 4785745, 2);
INSERT INTO `sgu_empleado` (`id`, `nombre`, `apellido`, `cedula`, `idtipoEmpleado`) VALUES (6, 'Carlos', 'Escalante', 12745963, 3);
INSERT INTO `sgu_empleado` (`id`, `nombre`, `apellido`, `cedula`, `idtipoEmpleado`) VALUES (2, 'José', 'Gonzáles', 7845856, 1);
INSERT INTO `sgu_empleado` (`id`, `nombre`, `apellido`, `cedula`, `idtipoEmpleado`) VALUES (3, 'Luis ', 'Sánchez', 9855474, 1);
INSERT INTO `sgu_empleado` (`id`, `nombre`, `apellido`, `cedula`, `idtipoEmpleado`) VALUES (4, 'Alejandro', 'Carrero', 1452145, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_estados`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_estados` (`id`, `estado`) VALUES (1, 'Táchira');
INSERT INTO `sgu_estados` (`id`, `estado`) VALUES (2, 'Mérida');
INSERT INTO `sgu_estados` (`id`, `estado`) VALUES (3, 'Zulia');
INSERT INTO `sgu_estados` (`id`, `estado`) VALUES (4, 'Distrito capital');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_lugar`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_lugar` (`id`, `lugar`, `idestados`) VALUES (1, 'UNET', 1);
INSERT INTO `sgu_lugar` (`id`, `lugar`, `idestados`) VALUES (2, 'Centro', 1);
INSERT INTO `sgu_lugar` (`id`, `lugar`, `idestados`) VALUES (3, 'Táriba', 1);
INSERT INTO `sgu_lugar` (`id`, `lugar`, `idestados`) VALUES (4, 'Cordero', 1);
INSERT INTO `sgu_lugar` (`id`, `lugar`, `idestados`) VALUES (5, 'Palmira', 1);
INSERT INTO `sgu_lugar` (`id`, `lugar`, `idestados`) VALUES (6, 'Santa Ana', 1);
INSERT INTO `sgu_lugar` (`id`, `lugar`, `idestados`) VALUES (7, 'Sto. Domingo', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_tipoViaje`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_tipoViaje` (`id`, `tipo`) VALUES (1, 'A');
INSERT INTO `sgu_tipoViaje` (`id`, `tipo`) VALUES (2, 'B');
INSERT INTO `sgu_tipoViaje` (`id`, `tipo`) VALUES (3, 'C');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_viaje`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_viaje` (`id`, `distanciaKm`, `idOrigen`, `idDestino`, `idtipo`, `viaje`) VALUES (1, 10, 1, 3, 1, 'UNET - Táriba');
INSERT INTO `sgu_viaje` (`id`, `distanciaKm`, `idOrigen`, `idDestino`, `idtipo`, `viaje`) VALUES (2, 11, 3, 1, 1, 'Táriba - UNET');
INSERT INTO `sgu_viaje` (`id`, `distanciaKm`, `idOrigen`, `idDestino`, `idtipo`, `viaje`) VALUES (3, 20, 1, 5, 1, 'UNET - Palmira');
INSERT INTO `sgu_viaje` (`id`, `distanciaKm`, `idOrigen`, `idDestino`, `idtipo`, `viaje`) VALUES (4, 20, 5, 1, 1, 'Palmira - UNET');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_kilometraje`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_kilometraje` (`id`, `fecha`, `lectura`, `idvehiculo`, `idhistoricoViajes`) VALUES (1, '2014-11-07', 125345, 1, NULL);
INSERT INTO `sgu_kilometraje` (`id`, `fecha`, `lectura`, `idvehiculo`, `idhistoricoViajes`) VALUES (2, '2014-11-07', 67412, 2, NULL);
INSERT INTO `sgu_kilometraje` (`id`, `fecha`, `lectura`, `idvehiculo`, `idhistoricoViajes`) VALUES (3, '2014-11-07', 147831, 3, NULL);
INSERT INTO `sgu_kilometraje` (`id`, `fecha`, `lectura`, `idvehiculo`, `idhistoricoViajes`) VALUES (4, '2014-11-07', 257896, 4, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_historicoEmpleados`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_historicoEmpleados` (`id`, `fechaInicio`, `fechaFin`, `idempleado`, `idvehiculo`) VALUES (1, '2014-12-19', '', 1, 1);
INSERT INTO `sgu_historicoEmpleados` (`id`, `fechaInicio`, `fechaFin`, `idempleado`, `idvehiculo`) VALUES (2, '2014-12-19', '', 2, 2);
INSERT INTO `sgu_historicoEmpleados` (`id`, `fechaInicio`, `fechaFin`, `idempleado`, `idvehiculo`) VALUES (3, '2014-12-19', '', 3, 3);
INSERT INTO `sgu_historicoEmpleados` (`id`, `fechaInicio`, `fechaFin`, `idempleado`, `idvehiculo`) VALUES (4, '2014-12-19', '', 4, 4);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_falla`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_falla` (`id`, `falla`) VALUES (1, 'El vehiculo se apagó de repente y no quizo encender de nuevo');
INSERT INTO `sgu_falla` (`id`, `falla`) VALUES (2, 'Se reventó la correa de los tiempos');
INSERT INTO `sgu_falla` (`id`, `falla`) VALUES (3, 'los frenos de atrás hacen un chillido fuerte');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_estacionServicio`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_estacionServicio` (`id`, `nombre`, `direccion`) VALUES (1, 'E/S paramillo', 'Zona industrial, paramillo');
INSERT INTO `sgu_estacionServicio` (`id`, `nombre`, `direccion`) VALUES (2, 'E/S las Vegas', 'Las vegas de Táriba');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_combust`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_combust` (`id`, `tipo`, `costoLitro`, `idtipoCombustible`) VALUES (1, 'Gasolina 91', 0.070, 1);
INSERT INTO `sgu_combust` (`id`, `tipo`, `costoLitro`, `idtipoCombustible`) VALUES (2, 'Gasolina 95', 0.095, 1);
INSERT INTO `sgu_combust` (`id`, `tipo`, `costoLitro`, `idtipoCombustible`) VALUES (3, 'Diesel super', 0.10, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_chasis`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_chasis` (`id`, `nombre`, `nroEjes`, `cantidadNormales`, `cantidadRepuesto`) VALUES (1, 'Automovil', 2, 4, 1);
INSERT INTO `sgu_chasis` (`id`, `nombre`, `nroEjes`, `cantidadNormales`, `cantidadRepuesto`) VALUES (2, 'Encava grande', 3, 10, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_posicionEje`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_posicionEje` (`id`, `posicionEje`) VALUES (1, 'Delantero');
INSERT INTO `sgu_posicionEje` (`id`, `posicionEje`) VALUES (2, 'Trasero');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_detalleEje`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_detalleEje` (`id`, `nroRuedas`, `idchasis`, `idposicionEje`, `nombre`) VALUES (1, 2, 1, 1, 1);
INSERT INTO `sgu_detalleEje` (`id`, `nroRuedas`, `idchasis`, `idposicionEje`, `nombre`) VALUES (2, 2, 1, 2, 2);
INSERT INTO `sgu_detalleEje` (`id`, `nroRuedas`, `idchasis`, `idposicionEje`, `nombre`) VALUES (3, 2, 2, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_posicionRueda`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_posicionRueda` (`id`, `posicionRueda`) VALUES (1, 'Derecho');
INSERT INTO `sgu_posicionRueda` (`id`, `posicionRueda`) VALUES (2, 'Izquierdo');
INSERT INTO `sgu_posicionRueda` (`id`, `posicionRueda`) VALUES (3, 'Delantero');
INSERT INTO `sgu_posicionRueda` (`id`, `posicionRueda`) VALUES (4, 'Trasero');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_estatusCaucho`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_estatusCaucho` (`id`, `estatusCaucho`) VALUES (1, 'Montado');
INSERT INTO `sgu_estatusCaucho` (`id`, `estatusCaucho`) VALUES (2, 'Rotado');
INSERT INTO `sgu_estatusCaucho` (`id`, `estatusCaucho`) VALUES (3, 'Desmontado');
INSERT INTO `sgu_estatusCaucho` (`id`, `estatusCaucho`) VALUES (4, 'Repuesto');
INSERT INTO `sgu_estatusCaucho` (`id`, `estatusCaucho`) VALUES (5, 'Por definir');
INSERT INTO `sgu_estatusCaucho` (`id`, `estatusCaucho`) VALUES (6, 'Por definir');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_detalleRueda`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_detalleRueda` (`id`, `idposicionRueda`, `iddetalleEje`, `idcaucho`) VALUES (1, 1, 1, 1);
INSERT INTO `sgu_detalleRueda` (`id`, `idposicionRueda`, `iddetalleEje`, `idcaucho`) VALUES (2, 2, 1, 1);
INSERT INTO `sgu_detalleRueda` (`id`, `idposicionRueda`, `iddetalleEje`, `idcaucho`) VALUES (3, 1, 2, 2);
INSERT INTO `sgu_detalleRueda` (`id`, `idposicionRueda`, `iddetalleEje`, `idcaucho`) VALUES (4, 2, 2, 2);
INSERT INTO `sgu_detalleRueda` (`id`, `idposicionRueda`, `iddetalleEje`, `idcaucho`) VALUES (5, 1, 3, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_fallaCaucho`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_fallaCaucho` (`id`, `falla`) VALUES (1, 'Perdió el aire completamente');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgu_accionCaucho`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `sgu_accionCaucho` (`id`, `accion`) VALUES (1, 'Renovar');
INSERT INTO `sgu_accionCaucho` (`id`, `accion`) VALUES (2, 'Rotación');
INSERT INTO `sgu_accionCaucho` (`id`, `accion`) VALUES (3, 'Reparar');

COMMIT;

